// tslint:disable
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, HttpQuery, throwIfRequired, encodeURI } from '../runtime';
import
{
    CreateGameResponse,
    GamePost,
    GameShortGet,
    HTTPValidationError,
    StatusGet,
    Token,
    User,
    UserCreate,
    UserShort,
} from '../models';
import { Action, AnyAction } from "redux";
import { map, mergeMap } from "rxjs/operators";
import { ofType, Effect, Epic } from "utils/Loop";

export interface AddToGameRequest
{
    gameId: string;
}

export interface ConnectToGameWithoutWebsocketRequest
{
    gameId: string;
}

export interface CreateGameRequest
{
    gamePost: GamePost;
}

export interface DeleteGameRequest
{
    gameId: string;
}

export interface GetGameStatusRequest
{
    gameId: string;
}

export interface GetUserByUuidRequest
{
    uuid: string;
}

export interface LoginRequest
{
    username: string;
    password: string;
    grantType?: string;
    scope?: string;
    clientId?: string;
    clientSecret?: string;
}

export interface RegisterRequest
{
    userCreate: UserCreate;
}

/**
 * no description
 */
class DefaultApi extends BaseAPI
{

    /**
     * Add To Game
     */
    addToGame = (requestParameters: AddToGameRequest): Observable<StatusGet> =>
    {
        throwIfRequired(requestParameters, 'gameId', 'addToGame');

        const headers: HttpHeaders = {
            // oauth required
            ...(this.configuration.accessToken && {
                Authorization: this.configuration.accessToken && (typeof this.configuration.accessToken === 'function'
                    ? this.configuration.accessToken('AuthBearer', [])
                    : this.configuration.accessToken)
            }),
        };

        return this.request<StatusGet>({
            path: '/games/{game_id}/add_to_game'.replace('{game_id}', encodeURI(requestParameters.gameId)),
            method: 'POST',
            headers,
        });
    }

    /**
     * Connect To Game Without Websocket
     */
    connectToGameWithoutWebsocket = (requestParameters: ConnectToGameWithoutWebsocketRequest): Observable<object> =>
    {
        throwIfRequired(requestParameters, 'gameId', 'connectToGameWithoutWebsocket');

        const headers: HttpHeaders = {
            // oauth required
            ...(this.configuration.accessToken && {
                Authorization: this.configuration.accessToken && (typeof this.configuration.accessToken === 'function'
                    ? this.configuration.accessToken('AuthBearer', [])
                    : this.configuration.accessToken)
            }),
        };

        return this.request<object>({
            path: '/games/{game_id}/connect'.replace('{game_id}', encodeURI(requestParameters.gameId)),
            method: 'POST',
            headers,
        });
    }

    /**
     * Create Game
     */
    createGame = (requestParameters: CreateGameRequest): Observable<CreateGameResponse> =>
    {
        throwIfRequired(requestParameters, 'gamePost', 'createGame');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
            // oauth required
            ...(this.configuration.accessToken && {
                Authorization: this.configuration.accessToken && (typeof this.configuration.accessToken === 'function'
                    ? this.configuration.accessToken('AuthBearer', [])
                    : this.configuration.accessToken)
            }),
        };

        return this.request<CreateGameResponse>({
            path: '/games/',
            method: 'POST',
            headers,
            body: requestParameters.gamePost,
        });
    }

    /**
     * Delete Game
     */
    deleteGame = (requestParameters: DeleteGameRequest): Observable<object> =>
    {
        throwIfRequired(requestParameters, 'gameId', 'deleteGame');

        const headers: HttpHeaders = {
            // oauth required
            ...(this.configuration.accessToken && {
                Authorization: this.configuration.accessToken && (typeof this.configuration.accessToken === 'function'
                    ? this.configuration.accessToken('AuthBearer', [])
                    : this.configuration.accessToken)
            }),
        };

        return this.request<object>({
            path: '/games/{game_id}'.replace('{game_id}', encodeURI(requestParameters.gameId)),
            method: 'DELETE',
            headers,
        });
    }

    /**
     * Get All Users
     */
    getAllUsers = (): Observable<Array<UserShort>> =>
    {
        const headers: HttpHeaders = {
            // oauth required
            ...(this.configuration.accessToken && {
                Authorization: this.configuration.accessToken && (typeof this.configuration.accessToken === 'function'
                    ? this.configuration.accessToken('AuthBearer', [])
                    : this.configuration.accessToken)
            }),
        };

        return this.request<Array<UserShort>>({
            path: '/users/all',
            method: 'GET',
            headers,
        });
    }

    /**
     * Get Game Status
     */
    getGameStatus = (requestParameters: GetGameStatusRequest): Observable<StatusGet> =>
    {
        throwIfRequired(requestParameters, 'gameId', 'getGameStatus');

        const headers: HttpHeaders = {
            // oauth required
            ...(this.configuration.accessToken && {
                Authorization: this.configuration.accessToken && (typeof this.configuration.accessToken === 'function'
                    ? this.configuration.accessToken('AuthBearer', [])
                    : this.configuration.accessToken)
            }),
        };

        return this.request<StatusGet>({
            path: '/games/{game_id}/status'.replace('{game_id}', encodeURI(requestParameters.gameId)),
            method: 'GET',
            headers,
        });
    }

    /**
     * Get Me
     */
    getMe = (): Observable<User> =>
    {
        const headers: HttpHeaders = {
            // oauth required
            ...(this.configuration.accessToken && {
                Authorization: this.configuration.accessToken && (typeof this.configuration.accessToken === 'function'
                    ? this.configuration.accessToken('AuthBearer', [])
                    : this.configuration.accessToken)
            }),
        };

        return this.request<User>({
            path: '/users/me',
            method: 'GET',
            headers,
        });
    }

    /**
     * Get Public Games
     */
    getPublicGames = (): Observable<Array<GameShortGet>> =>
    {
        const headers: HttpHeaders = {
            // oauth required
            ...(this.configuration.accessToken && {
                Authorization: this.configuration.accessToken && (typeof this.configuration.accessToken === 'function'
                    ? this.configuration.accessToken('AuthBearer', [])
                    : this.configuration.accessToken)
            }),
        };

        return this.request<Array<GameShortGet>>({
            path: '/games/',
            method: 'GET',
            headers,
        });
    }

    /**
     * Get User By Uuid
     */
    getUserByUuid = (requestParameters: GetUserByUuidRequest): Observable<User> =>
    {
        throwIfRequired(requestParameters, 'uuid', 'getUserByUuid');

        const headers: HttpHeaders = {
            // oauth required
            ...(this.configuration.accessToken && {
                Authorization: this.configuration.accessToken && (typeof this.configuration.accessToken === 'function'
                    ? this.configuration.accessToken('AuthBearer', [])
                    : this.configuration.accessToken)
            }),
        };

        const query: HttpQuery = {
            ...(requestParameters.uuid && { 'uuid': requestParameters.uuid }),
        };

        return this.request<User>({
            path: '/users/{username}',
            method: 'GET',
            headers,
            query,
        });
    }

    /**
     * Login
     */
    login = (requestParameters: LoginRequest): Observable<Token> =>
    {
        throwIfRequired(requestParameters, 'username', 'login');
        throwIfRequired(requestParameters, 'password', 'login');

        const formData = new FormData();
        if (requestParameters.grantType !== undefined) {
            formData.append('grant_type', requestParameters.grantType as any);
        }

        if (requestParameters.username !== undefined) {
            formData.append('username', requestParameters.username as any);
        }

        if (requestParameters.password !== undefined) {
            formData.append('password', requestParameters.password as any);
        }

        if (requestParameters.scope !== undefined) {
            formData.append('scope', requestParameters.scope as any);
        }

        if (requestParameters.clientId !== undefined) {
            formData.append('client_id', requestParameters.clientId as any);
        }

        if (requestParameters.clientSecret !== undefined) {
            formData.append('client_secret', requestParameters.clientSecret as any);
        }

        return this.request<Token>({
            path: '/auth/login',
            method: 'POST',
            body: formData,
        });
    }

    /**
     * Register
     */
    register = (requestParameters: RegisterRequest): Observable<User> =>
    {
        throwIfRequired(requestParameters, 'userCreate', 'register');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<User>({
            path: '/auth/register',
            method: 'POST',
            headers,
            body: requestParameters.userCreate,
        });
    }

}

export class Request<T, P, R, A extends Action> implements Effect<A> {
    readonly type = "Http/Request/Server";

    constructor(public readonly operationType: T, public readonly payload: P, public readonly onResponse: (payload: R) => A, public readonly tracker?: string)
    {
    }

    map<B extends Action>(mapper: (from: A) => B): Request<T, P, R, B>
    {
        return new Request(this.operationType, this.payload, p => mapper(this.onResponse(p)));
    }
}

export class WebAppClient
{
    static addToGame<A extends Action>(requestParameters: AddToGameRequest, onResponse: (response: StatusGet) => A): AddToGame<A>
    {

        return new Request("Http/Request/Server/AddToGame", requestParameters, onResponse);

    }

    static connectToGameWithoutWebsocket<A extends Action>(requestParameters: ConnectToGameWithoutWebsocketRequest, onResponse: (response: object) => A): ConnectToGameWithoutWebsocket<A>
    {

        return new Request("Http/Request/Server/ConnectToGameWithoutWebsocket", requestParameters, onResponse);

    }

    static createGame<A extends Action>(requestParameters: CreateGameRequest, onResponse: (response: CreateGameResponse) => A): CreateGame<A>
    {

        return new Request("Http/Request/Server/CreateGame", requestParameters, onResponse);

    }

    static deleteGame<A extends Action>(requestParameters: DeleteGameRequest, onResponse: (response: object) => A): DeleteGame<A>
    {

        return new Request("Http/Request/Server/DeleteGame", requestParameters, onResponse);

    }

    static getAllUsers<A extends Action>(onResponse: (response: Array<UserShort>) => A): GetAllUsers<A>
    {

        return new Request("Http/Request/Server/GetAllUsers", undefined, onResponse);

    }

    static getGameStatus<A extends Action>(requestParameters: GetGameStatusRequest, onResponse: (response: StatusGet) => A): GetGameStatus<A>
    {

        return new Request("Http/Request/Server/GetGameStatus", requestParameters, onResponse);

    }

    static getMe<A extends Action>(onResponse: (response: User) => A): GetMe<A>
    {

        return new Request("Http/Request/Server/GetMe", undefined, onResponse);

    }

    static getPublicGames<A extends Action>(onResponse: (response: Array<GameShortGet>) => A): GetPublicGames<A>
    {

        return new Request("Http/Request/Server/GetPublicGames", undefined, onResponse);

    }

    static getUserByUuid<A extends Action>(requestParameters: GetUserByUuidRequest, onResponse: (response: User) => A): GetUserByUuid<A>
    {

        return new Request("Http/Request/Server/GetUserByUuid", requestParameters, onResponse);

    }

    static login<A extends Action>(requestParameters: LoginRequest, onResponse: (response: Token) => A): Login<A>
    {

        return new Request("Http/Request/Server/Login", requestParameters, onResponse);

    }

    static register<A extends Action>(requestParameters: RegisterRequest, onResponse: (response: User) => A): Register<A>
    {

        return new Request("Http/Request/Server/Register", requestParameters, onResponse);

    }
}

export interface AddToGame<A extends Action> extends Request<"Http/Request/Server/AddToGame", AddToGameRequest, StatusGet, A>
{
    operationType: "Http/Request/Server/AddToGame";
}

export interface ConnectToGameWithoutWebsocket<A extends Action> extends Request<"Http/Request/Server/ConnectToGameWithoutWebsocket", ConnectToGameWithoutWebsocketRequest, object, A>
{
    operationType: "Http/Request/Server/ConnectToGameWithoutWebsocket";
}

export interface CreateGame<A extends Action> extends Request<"Http/Request/Server/CreateGame", CreateGameRequest, CreateGameResponse, A>
{
    operationType: "Http/Request/Server/CreateGame";
}

export interface DeleteGame<A extends Action> extends Request<"Http/Request/Server/DeleteGame", DeleteGameRequest, object, A>
{
    operationType: "Http/Request/Server/DeleteGame";
}

export interface GetAllUsers<A extends Action> extends Request<"Http/Request/Server/GetAllUsers", undefined, Array<UserShort>, A>
{
    operationType: "Http/Request/Server/GetAllUsers";
}

export interface GetGameStatus<A extends Action> extends Request<"Http/Request/Server/GetGameStatus", GetGameStatusRequest, StatusGet, A>
{
    operationType: "Http/Request/Server/GetGameStatus";
}

export interface GetMe<A extends Action> extends Request<"Http/Request/Server/GetMe", undefined, User, A>
{
    operationType: "Http/Request/Server/GetMe";
}

export interface GetPublicGames<A extends Action> extends Request<"Http/Request/Server/GetPublicGames", undefined, Array<GameShortGet>, A>
{
    operationType: "Http/Request/Server/GetPublicGames";
}

export interface GetUserByUuid<A extends Action> extends Request<"Http/Request/Server/GetUserByUuid", GetUserByUuidRequest, User, A>
{
    operationType: "Http/Request/Server/GetUserByUuid";
}

export interface Login<A extends Action> extends Request<"Http/Request/Server/Login", LoginRequest, Token, A>
{
    operationType: "Http/Request/Server/Login";
}

export interface Register<A extends Action> extends Request<"Http/Request/Server/Register", RegisterRequest, User, A>
{
    operationType: "Http/Request/Server/Register";
}

type RequestAPI<A extends Action> = AddToGame<A> | ConnectToGameWithoutWebsocket<A> | CreateGame<A> | DeleteGame<A> | GetAllUsers<A> | GetGameStatus<A> | GetMe<A> | GetPublicGames<A> | GetUserByUuid<A> | Login<A> | Register<A>;

export const defaultTracker = Symbol("defaultTracker");
const apiClient: DefaultApi = new DefaultApi();
const __unsafeHandleApiAction = (action: RequestAPI<AnyAction>) =>
{
    switch (action.operationType) {
        case "Http/Request/Server/AddToGame": return apiClient.addToGame(action.payload).pipe(map((response) => action.onResponse(response)));
        case "Http/Request/Server/ConnectToGameWithoutWebsocket": return apiClient.connectToGameWithoutWebsocket(action.payload).pipe(map((response) => action.onResponse(response)));
        case "Http/Request/Server/CreateGame": return apiClient.createGame(action.payload).pipe(map((response) => action.onResponse(response)));
        case "Http/Request/Server/DeleteGame": return apiClient.deleteGame(action.payload).pipe(map((response) => action.onResponse(response)));
        case "Http/Request/Server/GetAllUsers": return apiClient.getAllUsers().pipe(map((response) => action.onResponse(response)));
        case "Http/Request/Server/GetGameStatus": return apiClient.getGameStatus(action.payload).pipe(map((response) => action.onResponse(response)));
        case "Http/Request/Server/GetMe": return apiClient.getMe().pipe(map((response) => action.onResponse(response)));
        case "Http/Request/Server/GetPublicGames": return apiClient.getPublicGames().pipe(map((response) => action.onResponse(response)));
        case "Http/Request/Server/GetUserByUuid": return apiClient.getUserByUuid(action.payload).pipe(map((response) => action.onResponse(response)));
        case "Http/Request/Server/Login": return apiClient.login(action.payload).pipe(map((response) => action.onResponse(response)));
        case "Http/Request/Server/Register": return apiClient.register(action.payload).pipe(map((response) => action.onResponse(response)));
    }
};
export const __unsafeCallApi = (action: RequestAPI<AnyAction>, callback: (data: any) => void) =>
{
    const u = __unsafeHandleApiAction(action);
    u.subscribe(a =>
    {
        callback(a);
    });
};;

export const epic: Epic<Action, AnyAction> = (effect$) =>
    effect$.pipe(
        ofType<RequestAPI<Action>>("Http/Request/Server"),
        mergeMap(__unsafeHandleApiAction)
    );
