// tslint:disable
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface BodyLoginAuthLoginPost
 */
export interface BodyLoginAuthLoginPost {
    /**
     * @type {string}
     * @memberof BodyLoginAuthLoginPost
     */
    grantType?: string;
    /**
     * @type {string}
     * @memberof BodyLoginAuthLoginPost
     */
    username: string;
    /**
     * @type {string}
     * @memberof BodyLoginAuthLoginPost
     */
    password: string;
    /**
     * @type {string}
     * @memberof BodyLoginAuthLoginPost
     */
    scope?: string;
    /**
     * @type {string}
     * @memberof BodyLoginAuthLoginPost
     */
    clientId?: string;
    /**
     * @type {string}
     * @memberof BodyLoginAuthLoginPost
     */
    clientSecret?: string;
}
