// tslint:disable
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface GamePost
 */
export interface GamePost {
    /**
     * @type {string}
     * @memberof GamePost
     */
    name: string;
    /**
     * @type {string}
     * @memberof GamePost
     */
    password?: string;
    /**
     * @type {boolean}
     * @memberof GamePost
     */
    _private: boolean;
    /**
     * @type {string}
     * @memberof GamePost
     */
    description?: string;
    /**
     * @type {number}
     * @memberof GamePost
     */
    maxPlayers: number;
    /**
     * @type {boolean}
     * @memberof GamePost
     */
    hotJoin: boolean;
}
