// tslint:disable
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    GameStatus,
} from './';

/**
 * @export
 * @interface GameShortGet
 */
export interface GameShortGet {
    /**
     * @type {string}
     * @memberof GameShortGet
     */
    name: string;
    /**
     * @type {boolean}
     * @memberof GameShortGet
     */
    hasPassword: boolean;
    /**
     * @type {string}
     * @memberof GameShortGet
     */
    description?: string;
    /**
     * @type {number}
     * @memberof GameShortGet
     */
    players: number;
    /**
     * @type {number}
     * @memberof GameShortGet
     */
    maxPlayers: number;
    /**
     * @type {GameStatus}
     * @memberof GameShortGet
     */
    status: GameStatus;
    /**
     * @type {boolean}
     * @memberof GameShortGet
     */
    hotJoin: boolean;
    /**
     * @type {boolean}
     * @memberof GameShortGet
     */
    _private: boolean;
}
